package Main;

import administrador.ActividadAdministrador;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Admin extends javax.swing.JFrame {

    PreparedStatement prp = null;
    ResultSet result = null;
    Connection connection = null;
    String username;

    public Admin() {
        initComponents();
        ImageIcon ic = new ImageIcon(getClass().getResource("/Images/hospital.png"));
        this.setIconImage(ic.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdministradorUsuario = new javax.swing.JLabel();
        lblAdministradorContraseña = new javax.swing.JLabel();
        txtAdministradorUsuario = new javax.swing.JTextField();
        txtAdministradorContraseña = new javax.swing.JPasswordField();
        btnAdministradorInicio = new javax.swing.JButton();
        btnAdministradorAcceso = new javax.swing.JButton();
        lblAdministradorTitulo = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido Administrador.");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1000, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 550));

        lblAdministradorUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAdministradorUsuario.setText("Usuario:");

        lblAdministradorContraseña.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAdministradorContraseña.setText("Contraseña:");

        txtAdministradorUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdministradorUsuarioActionPerformed(evt);
            }
        });

        btnAdministradorInicio.setBackground(new java.awt.Color(0, 204, 204));
        btnAdministradorInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdministradorInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministradorInicio.setText("Inicio");
        btnAdministradorInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorInicioActionPerformed(evt);
            }
        });

        btnAdministradorAcceso.setBackground(new java.awt.Color(0, 153, 153));
        btnAdministradorAcceso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdministradorAcceso.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministradorAcceso.setText("Acceso");
        btnAdministradorAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorAccesoActionPerformed(evt);
            }
        });

        lblAdministradorTitulo.setAlignment(java.awt.Label.CENTER);
        lblAdministradorTitulo.setBackground(new java.awt.Color(0, 153, 153));
        lblAdministradorTitulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblAdministradorTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblAdministradorTitulo.setText("Sistema de gestión hospitalaria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(btnAdministradorInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btnAdministradorAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAdministradorContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdministradorUsuario))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtAdministradorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAdministradorContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblAdministradorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblAdministradorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdministradorUsuario)
                    .addComponent(txtAdministradorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdministradorContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdministradorContraseña))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdministradorInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministradorAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        lblAdministradorTitulo.getAccessibleContext().setAccessibleName("Sistema de gestión hospitalaria IMSS");

        getAccessibleContext().setAccessibleName("Bienvenido Adminsitrador");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministradorInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorInicioActionPerformed
        Hospital hospital = new Hospital();
        hospital.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAdministradorInicioActionPerformed

    private void btnAdministradorAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorAccesoActionPerformed
        connection = Connector.ConnectDb();
        String user = txtAdministradorUsuario.getText();
        String pass = String.valueOf(txtAdministradorContraseña.getPassword());

        try {
            String sql = "select usuario,contraseña from administrador where usuario='" + user + "'";
            prp = connection.prepareStatement(sql);
            result = prp.executeQuery();
            result.first();
            if (pass.equals(result.getString("contraseña"))) {
                ActividadAdministrador adminActivity = new ActividadAdministrador();
                adminActivity.setVisible(true);
                JOptionPane.showMessageDialog(null, "Inicio de sesión exitosa", "BIENVENIDO " + user, JOptionPane.INFORMATION_MESSAGE);
                dispose();
                username = user;
                adminActivity.User(username);
                connection.close();
            } else {
                JOptionPane.showMessageDialog(null, "Error de inicio de sesion", "Error", JOptionPane.WARNING_MESSAGE);
//                JOptionPane.showMessageDialog(null, "User or Password wrong.");
            }

        } catch (HeadlessException | SQLException e) {
//            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrecta.");
        }

    }//GEN-LAST:event_btnAdministradorAccesoActionPerformed

    private void txtAdministradorUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdministradorUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdministradorUsuarioActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministradorAcceso;
    private javax.swing.JButton btnAdministradorInicio;
    private javax.swing.JLabel lblAdministradorContraseña;
    private java.awt.Label lblAdministradorTitulo;
    private javax.swing.JLabel lblAdministradorUsuario;
    private javax.swing.JPasswordField txtAdministradorContraseña;
    private javax.swing.JTextField txtAdministradorUsuario;
    // End of variables declaration//GEN-END:variables
}
